; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[extra]
OTA_PASSWORD = "heslo1234"
; fine-grained PAT (Contents: Read pro repo ESP32_projekty) - pro stahovani releases zarizenim
GITHUB_TOKEN = "VLOZ_SEM_GITHUB_TOKEN"

[wifi]
ssid = "rt-software"
password = "Supertajneheslo2"

[env]
framework = arduino
monitor_speed = 115200
monitor_port = COM4
platform = espressif32
board = seeed_xiao_esp32s3
build_flags =
	'-DOTA_PASSWORD=${extra.OTA_PASSWORD}'
	'-DGITHUB_TOKEN=${extra.GITHUB_TOKEN}'
	'-DWIFI_SSID=${wifi.ssid}'
    '-DWIFI_PASS=${wifi.password}'
lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12
    bblanchon/ArduinoJson@^7

[env:seeed_xiao_esp32s3]
build_type = debug
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
debug_tool = esp-builtin
debug_init_break = 
	tbreak 
	setup
monitor_filters = 
	default 
	log2file
lib_deps = 
    ${env.lib_deps}
monitor_speed = 115200
monitor_port = COM4
upload_speed = 115200
upload_port = COM4
build_flags = 
	-DCORE_DEBUG_LEVEL=5
    ${env.build_flags}


[env:seeed_xiao_esp32s3_ota]
build_type = release
build_flags = 
	${env.build_flags}
upload_protocol = espota
upload_port = 192.168.1.99
upload_flags = 
	--auth=${extra.OTA_PASSWORD}
	--host_port=42123
lib_deps = 
	${env.lib_deps}
    
